"""Brain-Agent Loop runtime contracts and helpers."""

from .runtime import (
    AgentLoop,
    advance_loop_state,
    begin_step_record,
    build_step_context,
    complete_step_record,
    decide_loop_continuation,
    initialize_loop_state,
    planner_step_decision,
    project_recent_steps_for_brain,
    validate_brain_intent_patch,
    validate_step_decision,
)
from .types import (
    AskRequest,
    AutonomousNodeContext,
    BrainIntentPatch,
    BrainIntentPatchValidationError,
    CompletedStep,
    ContinuationBasis,
    HumanJudgmentAssessment,
    LoopContinuation,
    LoopContinuationDecision,
    LoopState,
    LoopStatus,
    PreparedStep,
    RuntimeOperationProposal,
    StepContext,
    StepDecision,
    StepKind,
    StepRecord,
    StepValidationError,
)

__all__ = [
    "AgentLoop",
    "AskRequest",
    "AutonomousNodeContext",
    "BrainIntentPatch",
    "BrainIntentPatchValidationError",
    "CompletedStep",
    "ContinuationBasis",
    "HumanJudgmentAssessment",
    "LoopContinuation",
    "LoopContinuationDecision",
    "LoopState",
    "LoopStatus",
    "PreparedStep",
    "RuntimeOperationProposal",
    "StepContext",
    "StepDecision",
    "StepKind",
    "StepRecord",
    "StepValidationError",
    "advance_loop_state",
    "begin_step_record",
    "build_step_context",
    "complete_step_record",
    "decide_loop_continuation",
    "initialize_loop_state",
    "planner_step_decision",
    "project_recent_steps_for_brain",
    "validate_brain_intent_patch",
    "validate_step_decision",
]
